name: ledger_cli
description: Parse ledger-cli ledger files
version: 0.1.1
homepage: https://github.com/amos-joshua/ledger_cli_dart

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  petitparser: ^5.1.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
