name: ledger_cli
description: Parse ledger-cli ledger files
version: 0.2.1
homepage: https://github.com/amos-joshua/ledger_cli_dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  petitparser: ^6.0.1
  csv: ^5.0.2
  intl: ^0.18.1

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.6
